### ISSUE TITLE
为什么不用lerna或者nx呢？

### ISSUE THREAD

**Issue by lidongtony** [wjq990112/nestjs-ssr#1]
1.为什么不用lerna或者nx做monorepo呢~
2.正在找nestjs的vite解决方案，不知道您的解决方案是否有效？我想用vue3+ssr+vite+nestjs来做官网的cms系统

**Comment by wjq990112** [comment]
> 1.为什么不用lerna或者nx做monorepo呢？
> 2.正在找nestjs的vite解决方案，不知道您的解决方案是否有效？我想用vue3+ssr+vite+nestjs来做官网的cms系统

1. 我理解并不需要 monorepo 的解决方案？引入一个技术方案之前需要确定是否是强需求，整体看下来 monorepo 并不是强需求
2. 可以作为调研材料，但不一定能使用到生产环境，不过可以尝试一下，有问题随时可以在这里反馈，带上最小可复现 demo，我都会及时回复
