### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by lastshrek** [wjq990112/nestjs-ssr#2]
运行了postbuild在dist文件里面npm install,
node main.js报错：
main.js
node:internal/fs/utils:345
    throw err;
    ^

Error: ENOENT: no such file or directory, scandir '/client/pages'
请问是哪里操作出现了问题吗？
想部署到服务器上。
谢谢

**Comment by wjq990112** [comment]
麻烦提供一下复现条件，包括 Node.js 版本，npm/yarn/pnpm 版本等信息 @lastshrek

**Comment by wjq990112** [comment]
另外，看起来你是在 window 上运行的，在 window 上文件路径需要额外进行处理，这里的错误提示是找不到文件导致的

**Comment by lastshrek** [comment]
没事啦 是我部署的问题 已经用上了 辛苦 ！
